[package]
name = "sas_run"
version = "0.1.5"
edition = "2024"
authors = ["ticktock"]
description = "用于windows下读取注册表中的SAS路径来执行指定的SAS程序文件"
documentation = "https://docs.rs/sas_run"
readme = "readme.md"
license = "MIT"
keywords = ["sas"]
repository = "https://github.com/TicklTock/sas_run"

[dependencies]
anyhow = "1.0.102"
thiserror = "2.0.18"
tokio = { version = "1.50.0", features = ["process"] }
winreg = "0.56.0"

[package.metadata.docs.rs]
targets = ["x86_64-pc-windows-msvc"]

